### ISSUE TITLE
Se debe refactorizar el codigo

### ISSUE THREAD

**Issue by evolentini** [franciscotimez/CESE_TSSE#2]
Se deben reemplazar las constantes por definiciones simbólicas y utilizar nombre de parámetros más significativos.

https://github.com/franciscotimez/CESE_TSSE/blob/6216b3bfcb7f875ab7885f9653a1c6d511f21170/leds/src/leds.c#L12-L18

**Comment by franciscotimez** [comment]
https://github.com/franciscotimez/CESE_TSSE/blob/0a2cf778ff094f1fbd1a506031222b0722262489/leds/src/leds.c#L8-L20
Código refactorizado.
